namespace AiComposer.Maui.Models;

/// <summary>Represents a file generated by a ticket run in the output folder.</summary>
public sealed class GeneratedFileItem
{
    /// <summary>Relative path of the file within the output workspace.</summary>
    public string RelativePath { get; init; } = string.Empty;

    /// <summary>Full absolute path to the file on disk.</summary>
    public string FullPath { get; init; } = string.Empty;

    /// <summary>Size of the file in bytes.</summary>
    public long SizeBytes { get; init; }

    /// <summary>Last write time of the file.</summary>
    public DateTimeOffset LastModified { get; init; }
}
